apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx
  labels:
    app: nginx
    version: "latest"
    env: "prod"
    tier: "frontend"
    managedby: "kubectl"
  annotations:
    "kubectl.kubernetes.io/last-applied-configuration": "{}"
    "date-created": "2023-09-03"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: "latest"
        env: "prod"
        tier: "frontend"
        managedby: "kubectl"
      annotations:  # This is the correct location for annotations in the pod template
        "build-version": "latest"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
